name: sodim
description: Una aplicación Flutter para gestión de órdenes de trabajo.

publish_to: 'KEVIN LAEL DE JESUS FLORES' # Este proyecto no se publica en pub.dev

version: 1.0.7

environment:
  sdk: ^3.7.0

dependencies:
  mobile_scanner: ^6.0.0
  onboarding_overlay: ^3.1.0  # o la versión más reciente
  flutter:
    sdk: flutter
  
# Información de la app
  package_info_plus: ^8.0.2
  
  # UI y animaciones
  animate_do: ^3.0.2
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  animated_text_kit: ^4.2.2

  # Navegación
  go_router: ^13.2.0

  # Logs y utilidades
  logger: ^2.0.2
  intl: ^0.18.0

  # HTTP y almacenamiento
  dio: ^5.3.2
  http: ^0.13.6
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.2.2
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.8.3

  signature: ^5.0.0

  device_info_plus: ^11.5.0
  crypto: ^3.0.3
  
  # Componentes adicionales
  flutter_typeahead: 5.2.0
  # flutter_keyboard_visibility: ^5.4.1 
  flutter_keyboard_visibility: ^6.0.0



  # Permisos y red
  
  permission_handler: ^11.0.1
  connectivity_plus: ^5.0.2

  # Descargar pdf
  printing: ^5.12.0
  pdf: ^3.10.4
  ftpconnect: ^2.0.3        # FTP / FTPS (explícito/implícito)
  dartssh2: ^2.8.2          # SFTP (opcional, por si usas SSH)
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  # image_path: "assets/icon/app_icon.png"  # Descomenta si tienes un ícono personalizado

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/Roboto-Bold.ttf
    - assets/images/SODIM.png
    - assets/images/SODIM1.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/SODIM.png"
